### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'biobert_ner/tmp/token_test_Thread-47.txt'

### ISSUE THREAD

**Issue by clouwer** [dmis-lab/bern#12]
I have managed to install BERN on centos7, under Python 3.7. When i send some requests, some requests return normal results, but some requests will report an error.  
The output tin the log file looks like the following:
`
Exception happened during processing of request from ('123.150.213.177', 41796)
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/root/anaconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/root/anaconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/root/anaconda3/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/root/anaconda3/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "server.py", line 320, in do_POST
    text, cur_thread_name, is_raw_text=True, reuse=False)
  File "server.py", line 460, in tag_entities
    self.biobert_recognize(dict_list, is_raw_text, cur_thread_name)
  File "server.py", line 501, in biobert_recognize
    thread_id=cur_thread_name)
  File "/bern/biobert_ner/utils.py", line 15, in with_profiling
    ret = fn(*args, **kwargs)
  File "/bern/biobert_ner/run_ner.py", line 488, in recognize
    with open(token_path, 'r') as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'biobert_ner/tmp/token_test_Thread-47.txt'
`

Then i check input_gnormplus and out_gnormplus. The input_gnormplus are normal but some out_gnormplus haven't write text. Like this:
`
[root@instance-1 output]# cat 64f84c92f898abb1b9e8c596a2719024e4b60782bb6c39c0075894d2.PubTator
64f84c92f898abb1b9e8c596a2719024e4b60782bb6c39c0075894d2|t|
64f84c92f898abb1b9e8c596a2719024e4b60782bb6c39c0075894d2|a|- No text -
`
Would you be able to let me know what the issue might be?
Thank you!

**Comment by avacaondata** [comment]
Did you solve the issue? I'm having the same problem @clouwer
