### ISSUE TITLE
ModuleNotFoundError: No module named 'xmltodict' when running `tail -F logs/nohup_BERN.out`

### ISSUE THREAD

**Issue by enzoampil** [dmis-lab/bern#13]
(env) ubuntu@ip-172-31-40-20:~/bern$ tail -F logs/nohup_BERN.out
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    from biobert_ner.run_ner import BioBERT, FLAGS
  File "/home/ubuntu/bern/biobert_ner/run_ner.py", line 21, in <module>
    from convert import preprocess
  File "/home/ubuntu/bern/convert.py", line 6, in <module>
    from download import query_pubtator2biocxml
  File "/home/ubuntu/bern/download.py", line 11, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'

**Comment by enzoampil** [comment]
Fixed this by installing `xmltodict` directly to python3.6 with `python3.6 -m pip install xmltodict`

**Comment by JonatanElihut** [comment]
sudo apt-get install -y python3-xmltodict     <---- install on ubuntu 18
