### ISSUE TITLE
Problems running bern in Docker

### ISSUE THREAD

**Issue by amalic** [dmis-lab/bern#16]
I am trying to dockerize your project but I am running into following issue when trying one of your test URL's.

see here: https://github.com/amalic/bern-docker

When I call: `http://localhost/?pmid=30429607&format=pubtator`
I get following error
```
Exception happened during processing of request from ('172.17.0.1', 40600)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "server.py", line 196, in do_GET
    self.biobert_recognize(dict_list, is_raw_text, cur_thread_name)
  File "server.py", line 490, in biobert_recognize
    thread_id=cur_thread_name)
  File "/app/biobert_ner/utils.py", line 15, in with_profiling
    ret = fn(*args, **kwargs)
  File "/app/biobert_ner/run_ner.py", line 474, in recognize
    example, self.FLAGS.max_seq_length, req_id, "test")
  File "/app/biobert_ner/run_ner.py", line 846, in convert_single_example
    self.write_tokens(ntokens, mode, req_id)
  File "/app/biobert_ner/run_ner.py", line 854, in write_tokens
    with open(path, 'a') as wf:
FileNotFoundError: [Errno 2] No such file or directory: 'biobert_ner/tmp/token_test_Thread-1.txt'
```

Starting the Docker container results in following console output
```
docker run -it --gpus all -p 80:8888 -v $PWD/externalData/GNormPlusJava/Dictionary/:/app/GNormPlusJava/Dictionary/ -v $PWD/externalData/tmVarJava/Database:/app/tmVarJava/Database -v $PWD/externalData/biobert_ner_models/:/app/bern/biobert_ner/ -v $PWD/externalData/data/:/app/normalization/data/ -v $PWD/externalData/resources/:/app/normalization/resources/ bern-docker
nohup: nohup: appending output to 'nohup.out'appending output to 'nohup.out'

root          6  0.0  0.0  37412  3432 pts/0    R+   03:14   0:00 java -Xmx16G -Xms16G -jar GNormPlusServer.jar 18895
root          7  0.0  0.0  37412  3524 pts/0    R+   03:14   0:00 java -Xmx8G -Xms8G -jar tmVar2Server.jar 18896
root          9  0.0  0.0  24628  4472 pts/0    R+   03:14   0:00 python3 normalizers/chemical_normalizer.py
root         10  0.0  0.0  24628  4712 pts/0    R+   03:14   0:00 python3 normalizers/species_normalizer.py
root         11  0.0  0.0  24628  4400 pts/0    R+   03:14   0:00 python3 normalizers/mutation_normalizer.py
root         12  0.0  0.0  37412  3440 pts/0    R+   03:14   0:00 java -Xmx16G -jar resources/normalizers/disease/disease_normalizer_19.jar
root         13  0.0  0.0  37412  2376 pts/0    R+   03:14   0:00 java -Xmx20G -jar gnormplus-normalization_19.jar
[23/Apr/2020 03:14:17.105468] Starting..
2020-04-23 03:14:17.118139: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-23 03:14:17.265485: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-23 03:14:17.268081: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3d8ae20 executing computations on platform CUDA. Devices:
2020-04-23 03:14:17.268144: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2020-04-23 03:14:17.288584: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3393280000 Hz
2020-04-23 03:14:17.290987: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3f2c490 executing computations on platform Host. Devices:
2020-04-23 03:14:17.291048: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-04-23 03:14:17.291345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:43:00.0
totalMemory: 10.91GiB freeMemory: 7.44GiB
2020-04-23 03:14:17.291440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-04-23 03:14:17.292519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-23 03:14:17.292554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-04-23 03:14:17.292616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-04-23 03:14:17.292743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 7239 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:43:00.0, compute capability: 6.1)
A GPU is available

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7fb16ec46840>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_eval_distribute': None, '_num_worker_replicas': 1, '_keep_checkpoint_max': 5, '_model_dir': './biobert_ner/pretrainedBERT/gene', '_master': '', '_log_step_count_steps': None, '_cluster': None, '_train_distribute': None, '_num_ps_replicas': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb16e05b9e8>, '_experimental_distribute': None, '_is_chief': True, '_protocol': None, '_evaluation_master': '', '_task_type': 'worker', '_global_id_in_cluster': 0, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_device_fn': None, '_tf_random_seed': None, '_save_checkpoints_secs': None, '_task_id': 0, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_session_config': gpu_options {
  allow_growth: true
}
, '_save_checkpoints_steps': 1000, '_save_summary_steps': 100}
INFO:tensorflow:_TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7fb04042a378>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_eval_distribute': None, '_num_worker_replicas': 1, '_keep_checkpoint_max': 5, '_model_dir': './biobert_ner/pretrainedBERT/disease', '_master': '', '_log_step_count_steps': None, '_cluster': None, '_train_distribute': None, '_num_ps_replicas': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb04043b9b0>, '_experimental_distribute': None, '_is_chief': True, '_protocol': None, '_evaluation_master': '', '_task_type': 'worker', '_global_id_in_cluster': 0, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_device_fn': None, '_tf_random_seed': None, '_save_checkpoints_secs': None, '_task_id': 0, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_session_config': gpu_options {
  allow_growth: true
}
, '_save_checkpoints_steps': 1000, '_save_summary_steps': 100}
INFO:tensorflow:_TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7fb0403c0488>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_eval_distribute': None, '_num_worker_replicas': 1, '_keep_checkpoint_max': 5, '_model_dir': './biobert_ner/pretrainedBERT/drug', '_master': '', '_log_step_count_steps': None, '_cluster': None, '_train_distribute': None, '_num_ps_replicas': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb04043bac8>, '_experimental_distribute': None, '_is_chief': True, '_protocol': None, '_evaluation_master': '', '_task_type': 'worker', '_global_id_in_cluster': 0, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_device_fn': None, '_tf_random_seed': None, '_save_checkpoints_secs': None, '_task_id': 0, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_session_config': gpu_options {
  allow_growth: true
}
, '_save_checkpoints_steps': 1000, '_save_summary_steps': 100}
INFO:tensorflow:_TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7fb0403c0598>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_eval_distribute': None, '_num_worker_replicas': 1, '_keep_checkpoint_max': 5, '_model_dir': './biobert_ner/pretrainedBERT/species', '_master': '', '_log_step_count_steps': None, '_cluster': None, '_train_distribute': None, '_num_ps_replicas': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb04043bbe0>, '_experimental_distribute': None, '_is_chief': True, '_protocol': None, '_evaluation_master': '', '_task_type': 'worker', '_global_id_in_cluster': 0, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_device_fn': None, '_tf_random_seed': None, '_save_checkpoints_secs': None, '_task_id': 0, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_session_config': gpu_options {
  allow_growth: true
}
, '_save_checkpoints_steps': 1000, '_save_summary_steps': 100}
INFO:tensorflow:_TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
BioBERT init_t 0.592 sec.
[23/Apr/2020 03:14:17.886905] Starting server at http://0.0.0.0:8888
gid2oid loaded 59849
goid2goid loaded 3468
gene meta #ids 42916, #ext_ids 42916
disease meta #ids 12122, #ext_ids 15040
chem meta #ids 179063, #ext_ids 179463
code2mirs size 9447
mirbase_id2mirna_id size 14945
mirna_id2accession size 6308
# of pathway regex 514
```

**Comment by amalic** [comment]
fixed it. had the wrong directory mounted

**Comment by avacaondata** [comment]
@amalic excuse me, how did you fix this?? I'm having the same problem: FileNotFoundError: [Errno 2] No such file or directory: 'biobert_ner/tmp/token_test_Thread-10.txt' using your docker version.
