### ISSUE TITLE
 lib/PAM140-6.txt (No such file or directory)

### ISSUE THREAD

**Issue by wanguan2000** [dmis-lab/bern#25]
java -Xmx8G -Xms8G -jar tmVar2Server.jar 18896
Starting tmVar 2.0 Service at 172.17.0.7:18896
Reading POS tagger model from lib/taggers/english-left3words-distsim.tagger ... done [0.6 sec].
Exception in thread "main" java.io.FileNotFoundException: lib/PAM140-6.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at kr.ac.korea.dmis.tmVar2.<init>(tmVar2.java:66)
	at kr.ac.korea.dmis.tmVar2Server.<init>(tmVar2Server.java:24)
	at kr.ac.korea.dmis.tmVar2Server.main(tmVar2Server.java:72)

**Comment by wanguan2000** [comment]
tmVarJava/lib
